You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.


class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char,int>map;
        for(auto x:s)
        map[x]++;           //finding occurences of all the characters

        for(auto x:t){
            if(map.find(x)==map.end())
            return x;           //if not found then return the character and that is the answer
            if(map[x]>1)
            map[x]--;       //decreasing the frequency of the character
            else
            map.erase(x);     //erasing the key if the occurence of the character is 1
            
        }


        return '1';  //never reached 
        
    }
};
